import { MenuItem, Location, Extra } from "./types";

export const sauces: Extra[] = [
  { id: "ranch", name: "Ranch omáčka", price: 25 },
  { id: "bbq", name: "BBQ omáčka", price: 25 },
  { id: "honey-mustard", name: "Medovo-hořčičná", price: 25 },
  { id: "garlic", name: "Česneková", price: 20 },
  { id: "spicy", name: "Pálivá sriracha", price: 25 },
  { id: "cheese", name: "Sýrová omáčka", price: 30 },
];

export const burgerExtras: Extra[] = [
  { id: "extra-cheese", name: "Extra sýr", price: 25 },
  { id: "bacon", name: "Slanina", price: 35 },
  { id: "jalapeno", name: "Jalapeño", price: 20 },
  { id: "egg", name: "Vejce", price: 25 },
  { id: "avocado", name: "Avokádo", price: 40 },
  { id: "onion-rings", name: "Cibulové kroužky", price: 30 },
];

export const healthyExtras: Extra[] = [
  { id: "extra-avocado", name: "Extra avokádo", price: 45 },
  { id: "poached-egg", name: "Zastřené vejce", price: 30 },
  { id: "feta", name: "Feta sýr", price: 35 },
  { id: "nuts", name: "Ořechy a semínka", price: 25 },
  { id: "hummus", name: "Hummus", price: 30 },
];

export const menuItems: MenuItem[] = [
  // FIT MENU - Dopolední zdravé jídlo
  {
    id: "avocado-toast",
    name: "Avokádový toast",
    description: "Křupavý toast s čerstvým avokádem, cherry rajčaty, fetou a microgreens. Posypané semínky.",
    price: 189,
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80",
    category: "fit",
    tags: ["Vegetariánské", "Zdravé"],
    extras: healthyExtras,
  },
  {
    id: "scrambled-eggs",
    name: "Míchaná vajíčka",
    description: "Nadýchaná míchaná vajíčka s pažitkou, podávané s celozrnným toastem a čerstvou zeleninou.",
    price: 149,
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
    category: "fit",
    tags: ["Protein", "Snídaně"],
    extras: healthyExtras,
  },
  {
    id: "chicken-vegetables",
    name: "Kuřecí prsa se zeleninou",
    description: "Grilovaná kuřecí prsa s mixem grilované zeleniny - cuketa, paprika, brokolice. Lehký bylinkový dresink.",
    price: 229,
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80",
    category: "fit",
    tags: ["Protein", "Low carb"],
    extras: healthyExtras,
  },
  {
    id: "protein-waffles",
    name: "Proteinové waffle s ovocem",
    description: "Domácí waffle z ovesných vloček s čerstvým ovocem, řeckým jogurtem a lžící medu.",
    price: 179,
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=800&q=80",
    category: "fit",
    tags: ["Snídaně", "Sladké"],
    extras: healthyExtras,
  },
  {
    id: "fruit-pancakes",
    name: "Palačinky s ovocem",
    description: "Nadýchané palačinky s čerstvými lesními plody, banánem a javorovým sirupem.",
    price: 169,
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
    category: "fit",
    tags: ["Snídaně", "Sladké"],
    extras: healthyExtras,
  },
  {
    id: "smoothie-bowl",
    name: "Smoothie Bowl",
    description: "Acai smoothie bowl s granolou, čerstvým ovocem, kokosovými chipsy a chia semínky.",
    price: 199,
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80",
    category: "fit",
    tags: ["Vegan", "Superfood"],
    extras: healthyExtras,
  },
  {
    id: "egg-benedict",
    name: "Vejce Benedikt",
    description: "Pošírovaná vejce na opečeném anglickém muffinu s uzeným lososem, holandskou omáčkou a čerstvou pažitkou.",
    price: 219,
    image: "/images/menu/egg-benedict.png",
    category: "fit",
    tags: ["Snídaně", "Klasika"],
    extras: healthyExtras,
  },
  {
    id: "salmon-poke",
    name: "Lososový Poke Bowl",
    description: "Čerstvý losos, edamame, avokádo, ředkvičky a okurka na rýžovém lůžku se sezamem.",
    price: 249,
    image: "/images/menu/salmon-poke.png",
    category: "fit",
    tags: ["Ryba", "Čerstvé"],
    extras: healthyExtras,
  },

  // FAT MENU - Odpolední prasárny
  {
    id: "chicken-strips",
    name: "Kuřecí stripsy",
    description: "Křupavé kuřecí stripsy v pikantním těstíčku. Podávané s výběrem omáček - bezedné refilly!",
    price: 199,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80",
    category: "fat",
    tags: ["Kuřecí", "Bezedné omáčky"],
    extras: sauces,
  },
  {
    id: "cheese-fries",
    name: "Sýrové hranolky se slaninou",
    description: "Křupavé hranolky zalité roztaveným čedarem, posypané křupavou slaninou a jarní cibulkou.",
    price: 169,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&q=80",
    category: "fat",
    tags: ["Sýr", "Slanina"],
    extras: sauces,
  },
  {
    id: "big-mac-maxi",
    name: "Big Mac MAXI",
    description: "Legendární burger v naší XXL verzi. Tři masové pláty, speciální omáčka, salát, sýr, okurky a cibule.",
    price: 289,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    category: "fat",
    tags: ["Burger", "XXL"],
    extras: burgerExtras,
  },
  {
    id: "loaded-wrap",
    name: "Loaded Wrap",
    description: "Tortilla plná kuřecího masa, sýru, zeleniny a naší speciální omáčky. Doslova přetéká chutí!",
    price: 179,
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
    category: "fat",
    tags: ["Wrap", "Plný omáčky"],
    extras: sauces,
  },
  {
    id: "double-bacon-burger",
    name: "Double Bacon Burger",
    description: "Dva hovězí plátky, dvojitá porce slaniny, cheddar, karamelizovaná cibulka a BBQ omáčka.",
    price: 269,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&q=80",
    category: "fat",
    tags: ["Burger", "Slanina"],
    extras: burgerExtras,
  },
  {
    id: "pulled-pork-burger",
    name: "BBQ Pulled Pork Burger",
    description: "Burger s trhaným vepřovým masem, coleslaw salátem, sýrem cheddar a porcí křupavé cibulky.",
    price: 259,
    image: "/images/menu/pulled-pork-burger.png",
    category: "fat",
    tags: ["Burger", "Trhané"),
    extras: burgerExtras,
  },
  {
    id: "mac-and-cheese",
    name: "Sýrové Mac & Cheese",
    description: "Krémové těstoviny se sýrovou omáčkou a křupavou slaninou, zapečené dozlatova.",
    price: 189,
    image: "/images/menu/mac-and-cheese.png",
    category: "fat",
    tags: ["Sýr", "Americká"),
    extras: sauces,
  },
  {
    id: "onion-rings",
    name: "Mega cibulové kroužky",
    description: "Obří porce křupavých cibulových kroužků v pivním těstíčku. S ranch a BBQ dipem.",
    price: 129,
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=800&q=80",
    category: "fat",
    tags: ["Snack", "Křupavé"],
    extras: sauces,
  },
  {
    id: "chili-cheese-dog",
    name: "Chili Cheese Dog",
    description: "Párek v rohlíku s domácím chili con carne, rozpuštěným čedarem a jalapeños.",
    price: 159,
    image: "https://images.unsplash.com/photo-1612392062126-2f0e26e10ded?w=800&q=80",
    category: "fat",
    tags: ["Hot dog", "Pálivé"],
    extras: burgerExtras,
  },
  {
    id: "chicken-bucket",
    name: "Chicken Bucket",
    description: "Kyblík plný smažených kuřecích křidélek a stehýnek. Pro 2-3 osoby. S výběrem omáček.",
    price: 399,
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&q=80",
    category: "fat",
    tags: ["Kuřecí", "Sdílení"],
    extras: sauces,
  },
  {
    id: "monster-milkshake",
    name: "Monster Milkshake",
    description: "Extrémní čokoládový shake s porcí šlehačky, brownies a čokoládovým topingem.",
    price: 149,
    image: "/images/menu/monster-milkshake.png",
    category: "fat",
    tags: ["Slané", "XXL"),
    extras: sauces,
  },

];

export const locations: Location[] = [
  {
    id: "prague",
    name: "Fit & Fat Praha",
    address: "Národní třída 25",
    city: "Praha 1",
    phone: "+420 123 456 789",
    hours: "Po-Ne: 8:00 - 22:00",
    coordinates: [50.0815, 14.4198],
  },
  {
    id: "tobolany",
    name: "Fit & Fat Tobolany",
    address: "Hlavní 42",
    city: "Tobolany u Prahy",
    phone: "+420 987 654 321",
    hours: "Po-Ne: 8:00 - 21:00",
    coordinates: [50.0397, 14.5513],
  },
];

export const deliveryZone = {
  center: [50.0755, 14.4378] as [number, number],
  radiusKm: 15,
};
